apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example

commonLabels:
  app.kubernetes.io/name: example

resources:
  - resources/deployment.yaml
  - resources/service.yaml
